# Generated by Django 4.1.7 on 2023-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="preferences",
        ),
        migrations.AddField(
            model_name="driver",
            name="preference_0",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driver",
            name="preference_1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driver",
            name="preference_2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driver",
            name="preference_3",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="driver",
            name="dni",
            field=models.ImageField(blank=True, null=True, upload_to="drivers/dnis/"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="driver_license",
            field=models.ImageField(
                blank=True, null=True, upload_to="drivers/driver_licenses/"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="sworn_declaration",
            field=models.ImageField(
                blank=True, null=True, upload_to="drivers/sworn_declarations/"
            ),
        ),
    ]
