# Generated by Django 4.1.7 on 2023-03-27 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="routines",
        ),
    ]
