# Generated by Django 4.1.7 on 2023-04-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0002_remove_driver_preferences_driver_preference_0_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="dni",
            new_name="dni_back",
        ),
        migrations.AddField(
            model_name="driver",
            name="dni_front",
            field=models.ImageField(blank=True, null=True, upload_to="drivers/dnis/"),
        ),
    ]
