# Generated by Django 4.1.7 on 2023-03-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0002_remove_driver_routines"),
        ("driver_routines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverroutine",
            name="driver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routines",
                to="drivers.driver",
            ),
        ),
    ]
