# Generated by Django 4.1.7 on 2023-03-27 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("driver_routines", "0002_driverroutine_driver"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driverroutine",
            old_name="is_single_ride",
            new_name="is_recurrent",
        ),
    ]
