# Generated by Django 4.1.7 on 2023-04-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_routines', '0005_alter_driverroutine_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverroutine',
            name='driver_notes',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
