# Generated by Django 4.1.7 on 2023-04-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_routines', '0006_driverroutine_driver_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverroutine',
            old_name='driver_notes',
            new_name='driver_note',
        ),
    ]
