# Generated by Django 4.1.7 on 2023-04-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("passengers", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassengerRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departure_time_start",
                    models.TimeField(verbose_name="Departure time window begin"),
                ),
                (
                    "departure_time_end",
                    models.TimeField(verbose_name="Departure time window end"),
                ),
                ("arrival_time", models.TimeField()),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Mon", "Mon"),
                            ("Tue", "Tue"),
                            ("Wed", "Wed"),
                            ("Thu", "Thu"),
                            ("Fri", "Fri"),
                            ("Sat", "Sat"),
                            ("Sun", "Sun"),
                        ],
                        max_length=7,
                        verbose_name="Day of week",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_routines_passenger",
                        to="locations.location",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_routines_passenger",
                        to="locations.location",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routines",
                        to="passengers.passenger",
                    ),
                ),
            ],
        ),
    ]
