# Generated by Django 4.1.7 on 2023-04-01 20:39

from django.db import migrations, models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0002_rename_name_location_address"),
        ("passengers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassengerRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departure_time_start",
                    models.TimeField(verbose_name="Departure time window begin"),
                ),
                (
                    "departure_time_end",
                    models.TimeField(verbose_name="Departure time window end"),
                ),
                ("arrival_time", models.TimeField()),
                (
                    "days_of_week",
                    models.CharField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ],
                        max_length=7,
                        verbose_name="Day of week",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_routines_passenger",
                        to="locations.location",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_routines_passenger",
                        to="locations.location",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routines",
                        to="passengers.passenger",
                    ),
                ),
            ],
        ),
    ]
