# Generated by Django 4.1.7 on 2023-04-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_routines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerroutine',
            old_name='days_of_week',
            new_name='day_of_week',
        ),
    ]
