# Generated by Django 4.1.7 on 2023-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passenger_routines", "0002_rename_days_of_week_passengerroutine_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passengerroutine",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Mon", "Mon"),
                    ("Tue", "Tue"),
                    ("Wed", "Wed"),
                    ("Thu", "Thu"),
                    ("Fri", "Fri"),
                    ("Sat", "Sat"),
                    ("Sun", "Sun"),
                ],
                max_length=7,
                verbose_name="Day of week",
            ),
        ),
    ]
