# Generated by Django 4.1.7 on 2023-03-27 23:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passenger_routines", "0003_alter_passengerroutine_days_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passengerroutine",
            name="days_of_week",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (0, "Mon"),
                        (1, "Tue"),
                        (2, "Wed"),
                        (3, "Thu"),
                        (4, "Fri"),
                        (5, "Sat"),
                        (6, "Sun"),
                    ],
                    max_length=7,
                    verbose_name="Day of week",
                ),
                size=None,
            ),
        ),
    ]
