# Generated by Django 4.1.7 on 2023-04-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ratings", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_trip",
                to="trips.trip",
            ),
        ),
        migrations.AddField(
            model_name="driverrating",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating_trip",
                to="trips.trip",
            ),
        ),
    ]
