# Generated by Django 4.2 on 2023-04-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_driverrating_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverrating',
            old_name='trip',
            new_name='trip_request',
        ),
    ]
