# Generated by Django 4.2 on 2023-04-09 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0003_rename_trip_driverrating_trip_request"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driverrating",
            old_name="preference_0",
            new_name="already_knew",
        ),
        migrations.RenameField(
            model_name="driverrating",
            old_name="preference_1",
            new_name="is_good_driver",
        ),
        migrations.RenameField(
            model_name="driverrating",
            old_name="preference_2",
            new_name="is_pleasant_driver",
        ),
        migrations.RemoveField(
            model_name="driverrating",
            name="preference_3",
        ),
    ]
