# Generated by Django 4.2 on 2023-04-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_validated_driver",
            field=models.BooleanField(default=False),
        ),
    ]
