# Generated by Django 4.1.7 on 2023-04-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_validated_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pilotuser',
            field=models.BooleanField(default=False),
        ),
    ]
