# Generated by Django 4.1.7 on 2023-04-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_has_module_perms_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_module_perms',
        ),
    ]
