# Generated by Django 4.2 on 2023-04-22 13:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_is_pilotuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                storage=users.models.OverwriteStorage(),
                upload_to=users.models.user_directory_path,
            ),
        ),
    ]
