# Generated by Django 4.1.7 on 2023-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_has_module_perms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_driver",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_passenger",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
