# Generated by Django 4.1.7 on 2023-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_is_driver_remove_user_is_passenger_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_driver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_passenger",
            field=models.BooleanField(default=True),
        ),
    ]
