# Generated by Django 4.1.7 on 2023-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_alter_transaction_receiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("DECLINED", "DECLINED"),
                    ("RECHARGE", "RECHARGE"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
