# Generated by Django 4.1.7 on 2023-03-04 17:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trips.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('discount_perc', models.FloatField()),
                ('lifts', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_num_seats', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
                ('end_location', models.CharField(max_length=256)),
                ('frecuency', models.CharField(max_length=256)),
                ('one_lift', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('discount_perc', models.FloatField()),
                ('lifts', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('disabled', models.BooleanField()),
                ('initial_lifts', models.IntegerField()),
                ('lifts_left', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('biography', models.CharField(max_length=256)),
                ('birth_date', models.DateField()),
                ('balance', models.BooleanField()),
                ('profile_pic', models.CharField(max_length=256)),
                ('verified', models.BooleanField(default=False)),
                ('entry_date', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256)),
                ('registration', models.CharField(max_length=256)),
                ('has_insurance', models.BooleanField(max_length=256)),
                ('insurance', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trips.passenger')),
                ('preferences', models.CharField(max_length=256)),
                ('biography', models.CharField(max_length=256)),
                ('has_driver_license', models.BooleanField()),
                ('has_sworn_declaration', models.BooleanField()),
                ('sworn_declaration', models.CharField(max_length=256)),
                ('driver_license', models.CharField(max_length=256)),
                ('dni_front', models.CharField(max_length=256)),
                ('dni_back', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TravellerRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('start_place', models.CharField(max_length=256)),
                ('end_place', models.CharField(max_length=256)),
                ('frequency', models.CharField(max_length=256)),
                ('time_diff_before', models.DateTimeField()),
                ('time_diff_after', models.DateTimeField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='TravellerDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField()),
                ('lifts_left', models.IntegerField()),
                ('active', models.BooleanField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.discountcode')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('mail', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_num_seats', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending start', 'Pending_start'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default=trips.models.LiftStatus['Pending_start'], max_length=256)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
                ('end_location', models.CharField(max_length=256)),
                ('driver_routine', models.ManyToManyField(to='trips.driverroutine')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualLift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
                ('end_location', models.CharField(max_length=256)),
                ('price', models.BooleanField()),
                ('status', models.CharField(choices=[('Pending start', 'Pending_start'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default=trips.models.LiftStatus['Pending_start'], max_length=256)),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.lift')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='FavDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('direction', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('cp', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='default_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_vehicle', to='trips.vehicle'),
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='trips.vehicle'),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=32)),
                ('CVC', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.driver'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.CharField(max_length=1024)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.driver'),
        ),
    ]
