# Generated by Django 4.1.7 on 2023-03-04 16:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trips.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dni', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('zip_code', models.CharField(max_length=256)),
                ('biography', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('money', models.BooleanField()),
                ('profile_pic', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256)),
                ('registration', models.CharField(max_length=256)),
                ('insurance', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trips.passenger')),
                ('driver_license', models.CharField(max_length=256)),
                ('VTC_license', models.CharField(max_length=256)),
                ('sign', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_seats', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_place', models.CharField(max_length=256)),
                ('end_place', models.CharField(max_length=256)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trips.passenger')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.vehicle')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_place', models.CharField(max_length=256)),
                ('end_place', models.CharField(max_length=256)),
                ('price', models.BooleanField()),
                ('state', models.CharField(choices=[('Active', 'ACTIVE'), ('Finished', 'FINISHED')], default=trips.models.TRIP_STATE['ACTIVE'], max_length=256)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('start_place', models.CharField(max_length=256)),
                ('end_place', models.CharField(max_length=256)),
                ('frequency', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('mail', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Discount_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('discount', models.BooleanField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('CVC', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Address_fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('zip_code', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.driver'),
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.passenger')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.driver')),
            ],
        ),
    ]
