# Generated by Django 4.1.7 on 2023-03-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='entry_date',
        ),
        migrations.AlterField(
            model_name='driverroutine',
            name='end_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='driverroutine',
            name='start_date',
            field=models.TimeField(),
        ),
    ]
