# Generated by Django 4.2 on 2023-04-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triprequest",
            name="note",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="triprequest",
            name="reject_note",
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
