# Generated by Django 4.1.7 on 2023-03-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_triprequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="triprequest",
            name="passenger",
        ),
    ]
