# Generated by Django 4.1.7 on 2023-04-23 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transaction_date"),
        ("trips", "0002_alter_triprequest_note_alter_triprequest_reject_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="triprequest",
            name="transaction",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="transactions.transaction",
            ),
            preserve_default=False,
        ),
    ]
