# Generated by Django 4.1.7 on 2023-05-03 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_alter_triprequest_note_alter_triprequest_reject_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="status",
        ),
    ]
