# Generated by Django 4.1.7 on 2023-04-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_triprequest_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='is_recurrent',
        ),
    ]
