# Generated by Django 4.1.7 on 2023-04-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transaction_date"),
        ("trips", "0003_triprequest_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triprequest",
            name="transaction",
            field=models.ForeignKey(
                default=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="transactions.transaction",
            ),
        ),
    ]
