# Generated by Django 4.1.7 on 2023-04-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_triprequest_is_recurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='reject_note',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
    ]
