# Generated by Django 4.1.7 on 2023-05-22 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_remove_trip_status"),
        ("trips", "0006_alter_triprequest_transaction"),
    ]

    operations = []
