# Generated by Django 4.1.7 on 2023-03-27 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("passengers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="routines",
        ),
    ]
