# Generated by Django 4.1.7 on 2023-03-27 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("passengers", "0002_remove_passenger_routines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passenger",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
