# Generated by Django 4.1.7 on 2023-04-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_alter_conversation_initiator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="conversation_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_set",
                to="chats.conversation",
            ),
        ),
    ]
