# Generated by Django 4.2 on 2023-04-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_alter_message_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read_by_recipient",
            field=models.BooleanField(default=False),
        ),
    ]
