# Generated by Django 4.2 on 2023-04-13 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0004_message_read_by_recipient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="conversation_id",
            new_name="conversation",
        ),
    ]
