# Generated by Django 4.1.7 on 2023-03-09 19:11

import bugalinkapp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('discount_perc', models.FloatField()),
                ('Rides', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_num_seats', models.IntegerField()),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('start_location', bugalinkapp.models.Coord(max_length=50, null=True)),
                ('end_location', bugalinkapp.models.Coord(max_length=50, null=True)),
                ('frecuency', models.CharField(max_length=256)),
                ('one_Ride', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('discount_perc', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('disabled', models.BooleanField(default=False)),
                ('initial_Rides', models.IntegerField()),
                ('Rides_left', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('biography', models.CharField(max_length=256)),
                ('birth_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256)),
                ('plate', models.CharField(max_length=256)),
                ('has_insurance', models.BooleanField(max_length=256)),
                ('insurance', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bugalinkapp.passenger')),
                ('preferences', models.CharField(max_length=2048)),
                ('biography', models.CharField(max_length=256)),
                ('has_driver_license', models.BooleanField(default=False)),
                ('has_sworn_declaration', models.BooleanField(default=False)),
                ('entry_date', models.DateField(null=True)),
                ('sworn_declaration', models.FileField(upload_to='')),
                ('driver_license', models.FileField(upload_to='')),
                ('dni_front', models.FileField(upload_to='')),
                ('dni_back', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_num_seats', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending start', 'Pending_start'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default=bugalinkapp.models.RideStatus['Pending_start'], max_length=256)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_location', bugalinkapp.models.Coord(max_length=50, null=True)),
                ('end_location', bugalinkapp.models.Coord(max_length=50, null=True)),
                ('driver_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.driverroutine')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('start_place', models.CharField(max_length=256)),
                ('end_place', models.CharField(max_length=256)),
                ('frequency', models.CharField(max_length=256)),
                ('time_diff_before', models.DurationField()),
                ('time_diff_after', models.DurationField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField()),
                ('Rides_left', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.discountcode')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_location', bugalinkapp.models.Coord(max_length=50, null=True)),
                ('end_location', bugalinkapp.models.Coord(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Ride_status', models.CharField(choices=[('Pending start', 'Pending_start'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default=bugalinkapp.models.RideStatus['Pending_start'], max_length=256)),
                ('acceptation_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Pending Confirmation', 'Pending_Confirmation')], default=bugalinkapp.models.AcceptationStatus['Pending_Confirmation'], max_length=256)),
                ('Ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.ride')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='FavDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('direction', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('location', bugalinkapp.models.Coord(max_length=50, null=True)),
                ('cp', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='default_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_vehicle', to='bugalinkapp.vehicle'),
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='bugalinkapp.vehicle'),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=32)),
                ('CVC', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ManyToManyField(to='bugalinkapp.driver'),
        ),
        migrations.CreateModel(
            name='PassengerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.CharField(max_length=1024)),
                ('IndividualRide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.individualride')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.driver'),
        ),
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.CharField(max_length=1024)),
                ('IndividualRide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.individualride')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.driver')),
            ],
        ),
    ]
