# Generated by Django 4.1.7 on 2023-03-25 13:39

import bugalinkapp.models
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('discount_perc', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rides', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Discount code',
                'verbose_name_plural': 'Discount codes',
            },
        ),
        migrations.CreateModel(
            name='DriverRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_num_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date_0', models.TimeField()),
                ('start_date_1', models.TimeField()),
                ('end_date', models.TimeField()),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('start_location', models.CharField(max_length=512)),
                ('end_location', models.CharField(max_length=512)),
                ('day', models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], default=bugalinkapp.models.Days['Mon'], max_length=26)),
                ('one_ride', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_note', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Driver routine',
                'verbose_name_plural': 'Driver routines',
            },
        ),
        migrations.CreateModel(
            name='IndividualRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptation_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Pending Confirmation', 'Pending_Confirmation')], default=bugalinkapp.models.AcceptationStatus['Pending_Confirmation'], max_length=256)),
                ('passenger_note', models.CharField(blank=True, max_length=1024, null=True)),
                ('decline_note', models.CharField(blank=True, max_length=1024, null=True)),
                ('n_seats', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Individual ride',
                'verbose_name_plural': 'Individual rides',
            },
        ),
        migrations.CreateModel(
            name='PassengerRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_longitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('start_latitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('end_longitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('end_latitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('start_location', models.CharField(max_length=512)),
                ('end_location', models.CharField(max_length=512)),
                ('day', models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], default=bugalinkapp.models.Days['Mon'], max_length=26)),
                ('end_date', models.TimeField()),
                ('start_time_initial', models.TimeField()),
                ('start_time_final', models.TimeField()),
            ],
            options={
                'verbose_name': 'Passenger routine',
                'verbose_name_plural': 'Passenger routines',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256, null=True)),
                ('plate', models.CharField(max_length=256, null=True)),
                ('insurance_status', models.CharField(choices=[('None', 'none'), ('Waiting Validation', 'Waiting_Validation'), ('Validated', 'Validated'), ('Cancelled', 'Cancelled')], default=bugalinkapp.models.DocumentValidationStatus['none'], max_length=32)),
                ('insurance', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'ordering': ('username',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bugalinkapp.user')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=bugalinkapp.models.get_file_path)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
            },
        ),
        migrations.CreateModel(
            name='RoutineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptation_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Pending Confirmation', 'Pending_Confirmation')], default=bugalinkapp.models.AcceptationStatus['Pending_Confirmation'], max_length=256)),
                ('driver_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.driverroutine')),
                ('passenger_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passengerroutine')),
            ],
            options={
                'verbose_name': 'Routine request',
                'verbose_name_plural': 'Routine requests',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seats', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending start', 'Pending_start'), ('Finished', 'Finished')], default=bugalinkapp.models.RideStatus['Pending_start'], max_length=256)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_longitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('start_latitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('end_longitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('end_latitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('start_location', models.CharField(max_length=512)),
                ('end_location', models.CharField(max_length=512)),
                ('driver_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.driverroutine')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.vehicle')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
            },
        ),
        migrations.CreateModel(
            name='PassengerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('preference_0', models.BooleanField(default=False)),
                ('preference_1', models.BooleanField(default=False)),
                ('preference_2', models.BooleanField(default=False)),
                ('individual_ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.individualride')),
            ],
            options={
                'verbose_name': 'Passenger rating',
                'verbose_name_plural': 'Passenger ratings',
            },
        ),
        migrations.AddField(
            model_name='individualride',
            name='passenger_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passengerroutine'),
        ),
        migrations.AddField(
            model_name='individualride',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.ride'),
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='default_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.vehicle'),
        ),
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('preference_0', models.BooleanField(default=False)),
                ('preference_1', models.BooleanField(default=False)),
                ('preference_2', models.BooleanField(default=False)),
                ('individual_ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.individualride')),
            ],
            options={
                'verbose_name': 'Driver rating',
                'verbose_name_plural': 'Driver ratings',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bugalinkapp.passenger')),
                ('preference_0', models.BooleanField(default=False)),
                ('preference_1', models.BooleanField(default=False)),
                ('preference_2', models.BooleanField(default=False)),
                ('preference_3', models.BooleanField(default=False)),
                ('dni_status', models.CharField(choices=[('None', 'none'), ('Waiting Validation', 'Waiting_Validation'), ('Validated', 'Validated'), ('Cancelled', 'Cancelled')], default=bugalinkapp.models.DocumentValidationStatus['none'], max_length=32)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('driver_license_status', models.CharField(choices=[('None', 'none'), ('Waiting Validation', 'Waiting_Validation'), ('Validated', 'Validated'), ('Cancelled', 'Cancelled')], default=bugalinkapp.models.DocumentValidationStatus['none'], max_length=32)),
                ('sworn_declaration_status', models.CharField(choices=[('None', 'none'), ('Waiting Validation', 'Waiting_Validation'), ('Validated', 'Validated'), ('Cancelled', 'Cancelled')], default=bugalinkapp.models.DocumentValidationStatus['none'], max_length=32)),
                ('sworn_declaration', models.FileField(blank=True, null=True, upload_to=bugalinkapp.models.get_file_path)),
                ('driver_license', models.FileField(blank=True, null=True, upload_to=bugalinkapp.models.get_file_path)),
                ('dni_front', models.FileField(blank=True, null=True, upload_to=bugalinkapp.models.get_file_path)),
                ('dni_back', models.FileField(blank=True, null=True, upload_to=bugalinkapp.models.get_file_path)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], default=bugalinkapp.models.TransactionStatus['Pending'], max_length=16)),
                ('is_refund', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='bugalinkapp.passenger')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='bugalinkapp.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.ride')),
                ('passenger_doing_reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_reporter', to='bugalinkapp.passenger')),
                ('passenger_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_reported', to='bugalinkapp.passenger')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
            options={
                'verbose_name': 'Paypal',
                'verbose_name_plural': 'Paypals',
            },
        ),
        migrations.AddField(
            model_name='passengerroutine',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger'),
        ),
        migrations.CreateModel(
            name='PassengerDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField()),
                ('rides_left', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.discountcode')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
            options={
                'verbose_name': 'Passenger Discount code',
                'verbose_name_plural': 'Passenger Discount codes',
            },
        ),
        migrations.AddField(
            model_name='individualride',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger'),
        ),
        migrations.CreateModel(
            name='IndividualDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('discount_perc', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_rides', models.IntegerField()),
                ('rides_left', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
            options={
                'verbose_name': 'Individual Discount code',
                'verbose_name_plural': 'Individual Discount codes',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=32)),
                ('CVC', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
            options={
                'verbose_name': 'Credit card',
                'verbose_name_plural': 'Credit cards',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.driver'),
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.driver'),
        ),
    ]
