# Generated by Django 4.1.7 on 2023-03-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugalinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverroutine',
            name='end_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='end_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='start_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='driverroutine',
            name='start_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='passengerroutine',
            name='end_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='passengerroutine',
            name='end_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='passengerroutine',
            name='start_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='passengerroutine',
            name='start_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='end_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='end_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
