# Generated by Django 4.1.7 on 2023-03-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugalinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
