# Generated by Django 4.1.7 on 2023-03-24 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugalinkapp', '0002_driverroutine_end_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
