# Generated by Django 4.1.7 on 2023-03-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugalinkapp', '0002_remove_individualride_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravellerDiscountCode',
            new_name='PassengerDiscountCode',
        ),
        migrations.RenameModel(
            old_name='TravellerRoutine',
            new_name='PassengerRoutine',
        ),
    ]
