# Generated by Django 4.1.7 on 2023-03-11 10:04

import bugalinkapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugalinkapp', '0003_rename_travellerdiscountcode_passengerdiscountcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptation_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Pending Confirmation', 'Pending_Confirmation')], default=bugalinkapp.models.AcceptationStatus['Pending_Confirmation'], max_length=256)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.driver')),
                ('driver_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.driverroutine')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugalinkapp.passenger')),
            ],
        ),
    ]
