# Generated by Django 4.1.7 on 2023-03-24 10:31

import bugalinkapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugalinkapp', '0003_alter_driver_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverroutine',
            name='day',
            field=models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], default=bugalinkapp.models.Days['Mon'], max_length=26),
        ),
        migrations.AlterField(
            model_name='passengerroutine',
            name='day',
            field=models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], default=bugalinkapp.models.Days['Mon'], max_length=26),
        ),
    ]
