# Generated by Django 4.1.7 on 2023-03-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugalinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dni_status',
            field=models.CharField(choices=[('None', 'None'), ('Waiting Validation', 'Waiting Validation'), ('Validated', 'Validated'), ('Cancelled', 'Cancelled')], default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_status',
            field=models.CharField(choices=[('None', 'None'), ('Waiting Validation', 'Waiting Validation'), ('Validated', 'Validated'), ('Cancelled', 'Cancelled')], default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='driver',
            name='sworn_declaration_status',
            field=models.CharField(choices=[('None', 'None'), ('Waiting Validation', 'Waiting Validation'), ('Validated', 'Validated'), ('Cancelled', 'Cancelled')], default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='individualride',
            name='acceptation_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Pending Confirmation', 'Pending Confirmation')], default='Pending Confirmation', max_length=256),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Pending start', 'Pending Start'), ('Finished', 'Finished')], default='Pending start', max_length=256),
        ),
        migrations.AlterField(
            model_name='routinerequest',
            name='acceptation_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Pending Confirmation', 'Pending Confirmation')], default='Pending Confirmation', max_length=256),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_status',
            field=models.CharField(choices=[('None', 'None'), ('Waiting Validation', 'Waiting Validation'), ('Validated', 'Validated'), ('Cancelled', 'Cancelled')], default='None', max_length=32),
        ),
    ]
