runtime: nodejs16

env: standard
service: default
env_variables:
  APPENGINE_URL: https://bugalink-379617.ew.r.appspot.com
  NODE_ENV: production
  NEXT_PUBLIC_BACKEND_URL: https://app.bugalink.es
  NEXT_PUBLIC_DOMAIN: https://app.bugalink.es
  NEXTAUTH_URL: https://app.bugalink.es
  NEXT_PUBLIC_DOMAIN_WS: app.bugalink.es
handlers:
  - url: /static
    static_dir: public

  - url: /.*
    script: auto
    secure: always
