runtime: nodejs16

env: flex
service: default
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 5
env_variables:
  APPENGINE_URL: https://bugalink-379617.ew.r.appspot.com
  NODE_ENV: production
  NEXT_PUBLIC_BACKEND_URL: https://app.bugalink.es
  NEXT_PUBLIC_DOMAIN: https://app.bugalink.es
  NEXTAUTH_URL: https://app.bugalink.es
  NEXT_PUBLIC_DOMAIN_WS: app.bugalink.es
handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: auto
    secure: always
